/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zypheos (https://sketchfab.com/zypheos)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/6b6a762bd8b34b6d9d46d44129b55037
title: Low Poly Head
*/

import * as THREE from 'three'
import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Plane_0: THREE.Mesh
  }
  materials: {
    Root: THREE.MeshStandardMaterial
  }
}

export default function LowPolyHead() {

  const { nodes, materials } = useGLTF('/low_poly_head/scene.gltf') as GLTFResult

  nodes.Plane_0.geometry.computeBoundingBox()
  return nodes.Plane_0.geometry.attributes.position
}

useGLTF.preload('/low_poly_head/scene.gltf')
